import http from 'node:http'; import { readFile, writeFile, access, mkdir } from 'node:fs/promises'; import { createReadStream } from 'node:fs'; import { extname, join, resolve } from 'node:path'; import { randomUUID } from 'node:crypto';
const root=resolve('.'), staticRoot=join(root,'dist'), storePath=join(root,'data/store.json'), seedPath=join(root,'data/store.example.json');
const iso=()=>new Date().toISOString(); const date=()=>iso().slice(0,10); const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
async function store(){try{return JSON.parse(await readFile(storePath,'utf8'))}catch{await mkdir(join(root,'data'),{recursive:true});const s=JSON.parse(await readFile(seedPath,'utf8'));await writeFile(storePath,JSON.stringify(s,null,2));return s}}
const save=s=>writeFile(storePath,JSON.stringify(s,null,2)); const body=req=>new Promise((resolve,reject)=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch{reject(Error('Invalid JSON'))}})});
function summary(s){const today=date(), records=s.attendance.filter(a=>a.attendanceDate===today), active=s.students.filter(x=>x.active);return {totalStudents:active.length,signedIn:records.filter(x=>x.status==='SIGNED_IN').length,signedOut:records.filter(x=>x.status==='SIGNED_OUT').length,todayAttendance:records.length,attendancePercentage:active.length?Math.round(records.length/active.length*100):0,recent:[...s.attendance].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,8).map(a=>enrich(s,a))}}
function enrich(s,a){return {...a,student:s.students.find(x=>x.id===a.studentId)}}
async function api(req,res,url){const s=await store(), path=url.pathname, method=req.method;
 if(method==='GET'&&path==='/api/dashboard')return send(res,200,summary(s));
 if(method==='GET'&&path==='/api/students')return send(res,200,s.students);
 if(method==='GET'&&path==='/api/attendance'){const q=url.searchParams;let a=s.attendance;if(q.get('date'))a=a.filter(x=>x.attendanceDate===q.get('date'));if(q.get('studentId'))a=a.filter(x=>x.studentId===q.get('studentId'));return send(res,200,a.map(x=>enrich(s,x)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)))}
 if(method==='POST'&&path==='/api/students'){const x=await body(req), required=['fullName','rollNumber','className','division'];if(required.some(k=>!String(x[k]||'').trim()))return send(res,400,{error:'Full name, roll number, class, and division are required.'});if(s.students.some(a=>a.rollNumber===x.rollNumber))return send(res,409,{error:'Roll number already exists.'});if(x.rfidUid&&s.students.some(a=>a.active&&a.rfidUid===String(x.rfidUid).toUpperCase()))return send(res,409,{error:'RFID UID is already assigned.'});const now=iso(), student={id:randomUUID(),fullName:x.fullName.trim(),rollNumber:x.rollNumber.trim(),className:x.className.trim(),division:x.division.trim(),email:String(x.email||'').trim(),rfidUid:x.rfidUid?String(x.rfidUid).toUpperCase().trim():null,active:true,createdAt:now,updatedAt:now};s.students.push(student);await save(s);return send(res,201,student)}
 if(method==='PATCH'&&path.startsWith('/api/students/')){const id=path.split('/').pop(),x=await body(req),student=s.students.find(a=>a.id===id);if(!student)return send(res,404,{error:'Student not found.'});const uid=x.rfidUid===undefined?student.rfidUid:(x.rfidUid?String(x.rfidUid).toUpperCase().trim():null);if(uid&&s.students.some(a=>a.id!==id&&a.active&&a.rfidUid===uid))return send(res,409,{error:'RFID UID is already assigned.'});Object.assign(student,{...x,rfidUid:uid,updatedAt:iso()});await save(s);return send(res,200,student)}
 if(method==='POST'&&path==='/api/attendance/scan'){const {rfidUid}=await body(req);const uid=String(rfidUid||'').toUpperCase().replace(/\s/g,'');if(!uid)return send(res,400,{error:'RFID UID is required.'});const student=s.students.find(x=>x.active&&x.rfidUid===uid);if(!student)return send(res,404,{error:'No active student is assigned to this RFID UID.',rfidUid:uid});let a=s.attendance.find(x=>x.studentId===student.id&&x.attendanceDate===date());const now=iso(), action=a?'SIGNED_OUT':'SIGNED_IN';if(a){if(a.status==='SIGNED_OUT')return send(res,409,{error:'This student has already signed out today.',student});a.signOutTime=now;a.status='SIGNED_OUT';a.updatedAt=now}else{a={id:randomUUID(),studentId:student.id,attendanceDate:date(),signInTime:now,signOutTime:null,status:'SIGNED_IN',createdAt:now,updatedAt:now};s.attendance.push(a)}await save(s);return send(res,200,{action,attendance:enrich(s,a),summary:summary(s)})}
 return send(res,404,{error:'API route not found'});
}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'};http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{if(url.pathname.startsWith('/api/'))return api(req,res,url);let file=url.pathname==='/'?'/src/index.html':url.pathname;let target=join(staticRoot,file);try{await access(target)}catch{target=join(staticRoot,'src/index.html')}res.writeHead(200,{'Content-Type':mime[extname(target)]||'application/octet-stream'});createReadStream(target).pipe(res)}catch(e){send(res,500,{error:e.message||'Server error'})}}).listen(process.env.PORT||3000,()=>console.log('RFID Attendance running on http://localhost:3000'));
